.TH TIC-TAC-TOE 1 "February 17, 2023" "Version 1.0.0" "User Manual"

.SH NAME
Tic-tac-toe \- an app that allows two players to play the classic tic-tac-toe game.

.SH SYNOPSIS
tic-tac-toe

.SH DESCRIPTION
Tic Tac Toe is a very famous board game, and it is very easy to implement in code. Because of this, I wanted to make it a bit more challenging without changing the basic concepts of the game. To achieve this, I implemented the game using the API System 5 Semaphores and shared memory of Linux to manage both players' turns and the board control.

.SH USAGE
The game prompts both players for the coordinates of their next move. First, it asks for the row, and then the column. Let's say that a coordinate is made up of (row, column). The board display is as follows:

.PP
.TS
tab(@);
c c c .
(0,0) (0,1) (0,2) 
(1,0) (1,1) (1,2)
(2,0) (2,1) (2,2)
.TE

.PP
For example:

.PP
.TS
tab(@);
c c c .
x - -  
- - -
- o -
.TE

.PP
If we ignore the '-' symbols, we can see that the 'x' player made a move at (0,0), and the 'o' player made a move at (2,1). NOTE: In the game, player1 is represented by 'x', and player2 is represented by 'o'.

.SH OPTIONS
No options are currently supported.

.SH SEE ALSO
No related manuals are available.

.SH BUGS
No bugs at the moment.

.SH AUTHOR
Filipondios
