.TH TIC-TAC-TOE 1 "April 5, 2023" "Version 2.0.0" "User Manual"

.SH NAME
Tic-tac-toe \- an app that allows one or two players to play the classic tic-tac-toe game.

.SH SYNOPSIS
ttt [OPTION]

.SH DESCRIPTION
Tic Tac Toe is a very famous board game, and it is very easy to implement in code. Because of this, I wanted to make it a bit more challenging without changing the basic concepts of the game. To achieve this, I implemented the game using the API System 5 Semaphores and shared memory of Linux to manage both players' turns and the board control. There is also a new feature available at the version 2.0.0 that allows you to play with an AI.

.SH USAGE
The game prompts the players for the coordinates of their next move. First, it asks for the row, and then the column. Let's say that a coordinate is made up of (row, column). The board display is as follows:

.PP
.TS
tab(@);
c c c .
(0,0) (0,1) (0,2) 
(1,0) (1,1) (1,2)
(2,0) (2,1) (2,2)
.TE

.PP
For example:

.PP
.TS
tab(@);
c c c .
x - -  
- - -
- o -
.TE

.PP
If we ignore the '-' symbols, we can see that the 'x' player made a move at (0,0), and the 'o' player made a move at (2,1). NOTE: In the game, player1 is represented by 'x', and player2 is represented by 'o'.

.SH OPTIONS

.PP
--ai-mode                Play 1v1 with an AI. This command can be followed only by
                         the '--max-depth' command and a number after this last
                         command one. Example: "--ai-mode --max-depth 9" (Only in 
                         this specific order).
.PP
--player-mode            Play 1v1 with physical players. No more
                         parameters are available after this command.
.PP
--max-depth <num>        Specify the maximum search depth for the AI. This can be
                         the third argument, being a number between 1 and 9.
.PP
--version                Display ttt version information. No more
                         parameters are available after this command.
.PP
--help                   Display a help message. No more parammeters are 
                         available after this command.

.SH SEE ALSO
No related manuals are available.

.SH BUGS
No bugs at the moment.

.SH AUTHOR
Filipondios
